export const products = [
  {
    id: 1,
    title: "Elegant watch for women",
    price: 890,
    description: "your perfect watch for everyday use",
    category: "women's watch",
    image: new URL("@/assets/image1.jpg", import.meta.url).href,
    stock: 12,
  },

  {
    id: 2,
    title: "comfortable adidas samba shoes",
    price: 2800,
    description: "Best choice for comfortable shoes",
    category: "adidas samba shoes for unisex",
    image: new URL("@/assets/image2.jpg", import.meta.url).href,
    stock: 17,
  },
  {
    id: 3,
    title: "classy dress for women",
    price: 1200,
    description: " Elegant short dress ",
    category: "women's clothes",
    image: new URL("@/assets/image3.jpg", import.meta.url).href,
    stock: 9,
  },
  {
    id: 4,
    title: "Elegant suit for men",
    price: 1500,
    description: "wedding suit for men",
    category: "men's clothes",
    image: new URL("@/assets/image4.jpg", import.meta.url).href,
    stock: 11,
  },
  {
    id: 5,
    title: "Elegant high heels for women",
    price: 1250,
    description: "Best choice for classy shoes",
    category: "women's shoes",
    image: new URL("@/assets/image5.jpg", import.meta.url).href,
    stock: 7,
  },

  {
    id: 6,
    title: "formal suit for women",
    price: 1600,
    description: "Best choice for formal suit",
    category: "women's clothes",
    image: new URL("@/assets/image6.jpg", import.meta.url).href,
    stock: 16,
  },

  {
    id: 7,
    title: "casual hoodie for men",
    price: 590,
    description: "comfortable hoodie for men",
    category: "men's clothes",
    image: new URL("@/assets/image7.jpg", import.meta.url).href,
    stock: 10,
  },

  {
    id: 8,
    title: "beautiful sweater for women",
    price: 870,
    description: "cozy sweater for women",
    category: "women's clothes",
    image: new URL("@/assets/image8.jpg", import.meta.url).href,
    stock: 17,
  },

  {
    id: 9,
    title: "classic shoes for men",
    price: 1150,
    description: "Best choice for classic shoes",
    category: "men's shoes",
    image: new URL("@/assets/image9.jpg", import.meta.url).href,
    stock: 14,
  },
];
